clipboard_control write-clipboard read-clipboard
mouse_map right press ungrabbed no_op
mouse_map right click ungrabbed copy_to_clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
background            #111111
foreground            #a0a0a0
cursor                #f0f0f0
selection_background  #3a3c4e
selection_foreground  #ffffff
color0 #191a23  # black (fg[black])
color1 #ea3b3b  # red (fg[red])
color2 #1dc44e  # green (fg[green])
color3 #e6d05a  # yellow (fg[yellow])
color4 #005a9e  # blue (fg[blue])
color5 #986ef2  # magenta (fg[magenta])
color6 #3fd1ff  # cyan (fg[cyan])
color7 #dedede  # white (fg[white])
color8 #303241  # bright black (fg_bold[black])
color9 #ff4763  # bright red (fg_bold[red])
color10 #3ef08f  # bright green (fg_bold[green])
color11 #ffe66d  # bright yellow (fg_bold[yellow])
color12 #2bb3e9  # bright blue (fg_bold[blue])
color13 #c499ff  # bright magenta (fg_bold[magenta])
color14 #5fe1ff  # bright cyan (fg_bold[cyan])
color15 #ffffff  # bright white (fg_bold[white])
font_family Iosevka Term Extended
font_size 12
disable_ligatures never
tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0 
tab_bar_style fade
tab_fade 0.25 1
map ctrl+tab        next_tab
map ctrl+shift+tab previous_tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map ctrl+equal  change_font_size all +2.0
map ctrl+plus   change_font_size all +2.0
map ctrl+kp_add change_font_size all +2.0
map ctrl+minus       change_font_size all -2.0
map ctrl+0 change_font_size all 0
